const  cn={
    lan:'cn',

    apps:{
        home:'首页',
        project:'项目',
        trade:'交易',
        score:'评分',
        mine:'我的',
        title:'获取验证码',
        tip:'复制成功',
        tip1:'检测到有最新版本',
        tip2:'是否前往下载更新?',
        tip3:'版本号无效',
        tip4:'此版本为强制更新，需更新完才能继续使用，请前往下载更新!',
    },
    login:{
        tip1:'请输入账号',
        tip2:'请输入验证码',
        tip3:'登录密码',
        tip4:'登陆',
        tip5:'注册',
        tip6:'密码登陆',
        tip7:'助记词登陆',
        tip8:'请输入密码'
    },

    register:{
        title:'注册',
        title1:'手机注册',
        title2:'邮箱注册',

        tip1:"请输入需要绑定的手机号码",
        tip2:"用户名（ID）",
        tip3:"请务必牢记您的用户名，登录时将会使用",

        tip4:"验证码",
        tip5:"请输入验证码",

        tip6:"密码",
        tip7:"请输入密码",

        tip8:"交易密码",
        tip9:"请输入交易密码",

        tip10:"推荐人",
        tip11:"请输入推荐人",

        tip12:"请输入需要绑定的邮箱",

        tip13:"请输入用户名（ID）",

        tip14:"验证码异常",
        area:"选择地区",
        getVerificationCode:"获取验证码",
    },

    invite:{
        title:'我的邀请链接',
        title1:'复制邀请码',
        title2:'复制邀请链接',
    },


    home:{
        title1:'评估ID:',
        title2:'点击复制',
        title3:'直播地址',
        title4:'点击复制',
        title5:'直播平台：',
        title6:'个人简介',
        title7:'官方公告',

    },
    project:{
        title1:'企业宣传册',
        title2:'企业宣传视频',
        title3:'APP操作视频'


    },
    score:{
        tip1:'请输入需要评分的网红账号',
        title:'评分',
        title1:'没有查找到该主播',
        title2:'没有查找到该主播',
        title3:'开始评分',
        title4:'评分系统即将开放！',
        title5:'丰富奖励,敬请期待！'

    },
    mine:{
        tip1:"请输入旧密码",
        tip2:'请输入新密码',
        tip3:'请再次输入您的新密码',

        tip4:'反馈成功',
        tip5:'请输入名称',
        tip6:'请选择性别',
        tip7:'个人信息修改成功',
        tip8:'收益已发放',
        tip9:'简体中文',
        tip10:'英语',
        tip11:'韩语',
        tip12:'功能正在开发中，敬请期待！',
        tip13:'-没有更多了，支持一下吧-',
        cancel:"取消",
        takeAPhoto:"拍照",
        image:"图片库",

        title1:'检查更新',
        title2:'语言设置',
        title3:'今日奖励',
        title4:'持币算力',
        title5:'推广算力',
        title6:'我的矿池',
        title7:'我的钱包',
        title8:'我的团队',
        title9:'活动',
        title10:'网红排行',
        title40:'项目',
        title41:'设置',
        title42:'关于我们',
        title43:'联系客服',
        title44:'节点申明',

        title11:'奖励',
        title12:'已发放总奖励',
        title13:'奖励记录',
        title14:'选择时间',
        title15:'请选语言',
        title16:'关于我们',
        title17: '我的团队',
        title18:'账户管理',
        title19:'节点发放规则',
        title20:'充币',
        title21:'充币码',
        title22:'复制钱包地址',
        title23: '复制成功',
        title24: '邮箱',
        title25: '当前已是最新版本',




    },
    setting:{
        tip1:"请输入旧密码",
        tip2:'请输入新密码',
        tip3:'请再次输入您的新密码',
        tip4:'修改密码成功',
        tip5:'请输入您的验证码',
        tip6:'请输入新手机号',
        tip7:'请输入新手机区号',
        tip8:'请输入新手验证码',
        tip9:'手机更换成功',
        tip10:'请输入昵称',



        title1:'更换密码',
        title2:'修改交易密码',
        title3:'更换手机号',
        title4:'旧密码',
        title5:'新密码',
        title6:'确认新密码',
        title7:'当前绑定手机号',
        title8:'验证当前手机',
        title9:'新绑定手机',
        title10:'验证绑定手机',
        title11:'确定',
        title12:'登录密码修改',
        title13:'交易密码修改',
        title14:'修改昵称',
        title15:'退出登陆',
        title16:'新昵称',
        title17:'确定',
        title18:'是否确定退出账号',

        takeAPhoto:"拍照",
        image:"图片库",

    },
    myPool:{
        tip1:'个人算力',
        tip2:'个人算力占比',
        tip3:'挖矿系数',
        tip4:'收益记录',
        tip5:'持币算力',
        tip6:'推广算力',
        tip7:'最低持币',
        tip8:'矿池余额',
        tip9:'算力分布',
        tip10:'钱包转入',
        tip11:'钱包转出',
        tip12:'请输入数量',
        tip13:'请输入交易密码',
        tip14:'算力:',
        tip15:'当前余额',
        tip16:'请输入交易密码',
        tip17:'今日收益',
        tip18:'最佳持币',
        tip19:'收益',
        tip20:'矿池金额:',
        tip21:'好友人数:',
        tip22:'团队有效人数:',
        tip23:'交易密码不正确',

        title:'我的矿池',
        title1:'确定',
        title2:'取消',
        title3:'算力分布',
        title4:"邀请算力",
        title5:"冰峰算力",
        title6:"青峰算力",
        title7:'持币算力',
        title8:'未生效持币算力',
        title9:'邀请算力分布',
        title10:'冰峰算力分布',
        title11:'青峰算力分布',
        title12:'收益时间',
        title13:'持币奖励',
        title14:'基金奖励',
        title15:'评分奖励',
        title16:'循环池奖励',
        title17:'收益明细',
        title18:'本日总收益',
        title19:'转入数量',
        title20:'交易密码',
        title26:'推广奖励',
        title27:'转出数量',
        title28:'团队总人数',
        title29:'团队总人数：',
        title30:'人',
        title31:'用户[USERS]',
        title32:'矿池金额[TAL]',
        title33:'新增算力',
        title34:'本周新增算力',
        title35:'本周新增人数：',
        title36:'确定锁仓',
        title37:'锁仓日期：',
        title38:'锁仓时长：',
        title39:'到期日期：',
        title40:'锁仓数量',
        title41:'继续锁仓',
        title42:'锁仓转入',
        title43:'锁仓转出',
        title44:'天',
    },
    fundPage:{
        tip:'基金奖励的Talenter将定期转出到此地址',
        tip1:'请输入数量',
        tip2:'请输入地址',
        tip3:'请输入密码',
        tip4:'转入成功',
        tip5:'转出成功',
        tip6:'续签成功',

        title:'网红基金',
        title1:'转入到基金',
        title2:'转出和续签',
        title3:'将钱包里的BTC导入到基金中，签约并保持锁仓（无转出行为），即可参与BTC网红基金发展，最新锁仓数量0.1BTC，签约手续费0.001BTC，一周续签一次，D+2日发放收益。',
        title4:'转入数量',
        title5:'手续费',
        title6:'请输入签约地址(建议使用交易所地址)',
        title7:'注意：如果是非talenter地址，奖励将无法找回',
        title8:'确定签约',
        title9:'可转出数量',
        title10:'签约生效数量',
        title11:'签约地址',
        title12:'注意：基金奖励将按照最新地址发放，即用户填写多个地址时，新的地址将覆盖老地址',
        title13:'全部转出到钱包',
        title14:'转出手续费',
        title15:'续签',
        title16:'续签手续费',
        title17:'交易密码',
        title18:'转账记录',
        title19:'签约时间',
        title20:'签约数量',
        title21:'手续费'
    },
    collideTrade:{
        tip1:'请输入消耗BTC',
        tip2:'请输入交易密码',
        tip3:'对撞成功',


        title:'对撞交易',
        title1:'交易密码',
        title2:'累计对撞数量',
        title3:'对撞数量',
        title4:'消耗BTC',
        title5:'交易密码',
        title6:'钱包余额',
        title7:'意：当对撞数量大于本层剩余数量时，超出的部分将会退还给用户',
        title8:'钱包余额',
        title9:'比特对撞',
        title10:'本层对撞剩余数量',
        title11:'我的BTC钱包余额',
        title12:'约',
        title13:'兑换比例',
        title14:'立即对撞',
        title15:'对撞记录',
        title16:'对撞数量',
        title17:'对撞比例',
        title18:'消耗BTC',
    },
    myWallet:{
        title:'我的钱包',
        title2:'代币种类',
        title3:'可用余额',
        title4:'冻结余额',
        title5:'资产估值',
        title6:'交易记录',
        title7:'转币',
        title8:'充币',
        title9:'转入成功',
        title10:'转入失败',
        title11:'转入处理中',
        title12:'转出成功',
        title13:'转出失败',
        title14:'转出处理中',
        title15:'转币',
        title16:'链上收款地址',
        title17:'好友收款地址',
        title18:'发送数量',
        title19:'密码',
        title20:'当前绑定的手机号/邮箱',
        title21:'验证码',
        title22:'手续费预估',
        title23:'余额',
        title24:'转入详情',
        title25:'转出详情',
        title26:'发款方',
        title27:'代币地址',
        title28:'用户地址',
        title29:'订单号',
        title30:'区块数',
        title31:'转入时间',
        title32:'复制邀请码',
        title33:'收益',
        title34:'交易密码',
        title35: '锁仓挖矿',
        title36: '去交易',
        title37: '选择TAL锁仓数量',
        title38: '选择TAL锁仓时长',
        title39:'枚',
        title40:'您的挖矿收益将于每日1更新8点发放',
        title41:'锁仓的TAL将进入矿次',
        title42:'确定锁仓',
        title43: '您的挖矿收益将于每日1更新8点发放',
        title44: '锁仓的TAL将进入矿池',
        title45: '锁仓记录',

        tip:'请输入收款地址',
        tip1:'请输入发送数量',
        tip2:'请输入密码',
        tip3:'请输入验证码',
        tip4:'请输入收款账号',
        tip5:'转账成功',
        tip6:'请输入交易密码',
        tip7:'提示',
        tip8:'30天\n（年化25%）',
        tip9:'60天\n（年化30%）',
        tip10:'90天\n（年化35%）',


    },
    feedback:{
        title:'联系客服',
        title1:'上传图片',
        title2:'请输入您的邮箱',
        title3:'内容描述',
        title4:'问题描述可编辑200字',
        title5:'添加图片(大小不超过1M)，最多上传三张',
        title6:'提交',

        tip:'请输入邮箱',
        tip1:'请输入问题描述',
        tip2:'反馈成功'

    },
    trade:{
        title:'交易所',
        title1:'交易所功能暂未开放\n 预计将于10月中旬项目公募后开放',
        title2:'敬请期待',
        title3:'买入',
        title4:'卖出',
        title5:'数量',
        title6:'价格',
        title7:'当前委托',
        title8:'历史记录',
        title9:'暂无数据！',
        title10:'撤销',
        title11:'价格[USDT]',
        title12:'数量[TAL]',
        title13:'实际成交[TAL]',
        title14:'全部委托',
        title15:'历史记录',
        title16:'成交明细',
        title17:'分钟',
        title18:'小时',
        title19:'日',
        title20:'周',
        title21:'高',
        title22:'低',
        title23:'24H',
        title24:'成交',
        title25: '时间',
        title26: '方向',
        title27: '价格[USDT]',
        title28: '数量[TAL]',




        tip:'交易所功能暂未开放,敬请期待!',
        tip1:'请输入价格',
        tip2:'请输入数量',
        tip3:'可用委托',
        tip4:'交易额 ',
        tip5:'买入TAL',
        tip6:'卖出TAL',


    },
    mnemonic:{
        title:'助记词登陆',
        title1:'助记词',
        title2:'私钥',
        title3:'开始导入',
        title4:'备份助记词',
        title5:'下一步',
        title6:'确定',
        title7:'*助记词顺序不正确，请检查',
        title8:'立即备份',
        title9:'TALENTER助记词',
        title10:'TALENTER地址',
        title11:'TALENTER私钥',
        title12:'完成',
        title13:'导出助记词',
        title14:'立即备份',

        tip:'请填写您的助记词，英文单词请按空格分隔单词',
        tip1:'请认真按顺序抄写下方12个助记词 \n我们将在下一步验证',
        tip2:'请将您抄下的12个单词按正确的顺序选择至下方',
        tip3:'您的身份助记词未备份，请务必记住助记词',
        tip4:'助记词可用于恢复身份下的钱包资产，防止密码、手机丢失等情况导致资产损失',
        tip5:'  认真抄写 安全保管 切勿泄露自己的私钥 \n钱包服务器不保管用户私钥，遗失无法找回',
        tip6:'地址助记词备份成功！',
        tip7:'请妥善保管您的助记词 \n请勿丢失或泄漏给他人',
        tip8:'请输入交易密码',
        tip9:'助记词输入不完整',
        tip10:'请输入助记词',
        tip11:'请输入私钥',

    },






}


export {
    cn
}
